import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-clerk-provider";
import { Toaster } from "@/components/ui/sonner";
import ModalProvider from "@/providers/modalProvider";
const inter = Inter({ subsets: ["latin"] });
import NextTopLoader from "nextjs-toploader"
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "TeamFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <NextTopLoader/>
        <ConvexClientProvider>
          <ModalProvider/>
          <Toaster />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
